### PR TITLE
Update site to use CWL css and remove template content

### PR DESCRIPTION
**Pull request by alexiswl**
## Changes

- [x] Update CSS to use CWL colours #2 
- [x] Reset template content
- [x] Added date, location? and reach out for more organisers #3 
- [x] Added call for submissions paragraph (below the note that the submissions will open in February) #13  / #7 @skanwal 
- [x] Waiting on #11 since this PR is rebased on the move-site branch
- [x] Announced that submissions will open in February (#10), do we need another sub-site for submissions and say coming soon?
- [x] Reformat call for submissions @kinow

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Checked out the repository code today for the first time. Great work setting this up! Simpler than I expected, really easy to test and modify :pray: thanks!

Here's what this branch looks like for me.

Screen Shot 2023-11-23 at 20 50 49-fullpage

@alexiswl what about this patch?

```diff
diff --git a/cwlcon2024-site/assets/main.css b/cwlcon2024-site/assets/main.css
index 24ab7e9..b46408e 100644
--- a/cwlcon2024-site/assets/main.css
+++ b/cwlcon2024-site/assets/main.css
@@ -4,7 +4,7 @@
  * I've listed them here so that a user may easily
  * do a search-and-replace for these to change the site theme.
  *   'Roboto',sans-serif; Font for the title text
- *   'Roboto-Slab',serif; Font for the body text 
+ *   'Roboto-Slab',serif; Font for the body text
  *   #fafafa; Background color of the site
  *   #505050; Foreground (text) color of the site
  *   #52739e; Navy, "Template" in the logo, current page in navigation, special titles in the Program
@@ -18,7 +18,7 @@
 *{
     border:0;
     font:inherit;
-    font-size:1em;
+    font-size:1rem;
     margin:0;
     padding:0;
     vertical-align:baseline;
@@ -28,11 +28,11 @@ body{
     background-color: #ffffff;
     background-size: cover;
     background-attachment: fixed;
-    color: #505050; 
+    color: #505050;
     text-align:left;
     font-family:'Roboto',sans-serif;
-    font-size:1em;
-    line-height:1.5em;
+    font-size:1rem;
+    line-height:1.5rem;
     margin: 60px auto;
     width: 1000px;
 }
@@ -42,31 +42,30 @@ a.current{color: #52739e;}
 a.current:hover{color: #e82945;}
 a:hover{color: #b2132e;}
 a:active{color: #e82945;}
-h1,h2,h3,h4{clear:left; color: #813c54; margin:1.5em 0em 1em 0em; font-family:'Roboto Slab',serif; text-shadow: 1px 1px 2px #d0d0d0;}
-h1{font-size:2.67em;}
-h2{font-size:2.00em;}
-h3{font-size:1.67em;}
-h4{font-size:1.33em;}
-p{list-style:none; margin:24px auto 24px auto; padding:0px; width:900px; text-align:left;}
+h1,h2,h3,h4{clear:left; color: #813c54; margin:1.5rem 0 1rem 0; font-family:'Roboto Slab',serif; text-shadow: 1px 1px 2px #d0d0d0;}
+h1{font-size:2.67rem;}
+h2{font-size:2.00rem;}
+h3{font-size:1.67rem;}
+h4{font-size:1.33rem;}
+p{list-style:none; margin:24px auto 24px auto; padding:0; width:900px; text-align:left;}
 li a, p a {text-decoration:underline; text-decoration-color:#b8860b;}
-ul{list-style:none; margin:24px auto 24px auto; padding:0px; width:800px; text-align:left;}
-ul li{list-style:none; margin:0px auto 0px auto; padding:0px; text-align:left;}
+ul{list-style:none; margin:24px auto 24px auto; padding:0; width:800px; text-align:left;}
+ul li{list-style:none; margin:0 auto 0 auto; padding:0; text-align:left;}
 i,em{font-style:italic;}
 b,strong{font-weight:bold;}
 sup{
     vertical-align: super;
-    font-size: 0.8em;
+    font-size: 0.8rem;
     line-height: 0;
 }
 sub{
     vertical-align: sub;
-    font-size: 0.8em;
+    font-size: 0.8rem;
     line-height: 0;
 }
 table{
     width: 1000px;
     margin: 12px auto 24px auto;
-    float: center;
     /* UNCOMMENT THIS FOR DEBUGGING THE ALIGNMENT */
     /*border: 1px solid black;*/
 }
@@ -78,52 +77,52 @@ th,td{
 
 /* Website Banner */
 .banner {position: relative; font-family:'Roboto Slab',serif;}
-.top-left {font-size:5.33em; color: #9b9b9b; background: #ffffff; text-align: center; width: 1000px; height: 67px; position: absolute; padding: 36px 0 0 0; top: 0px;}
-.bottom-right {font-size:2.33em; color: #8a2332; line-height: 1.5em; width: auto; height: 100px; padding: 0px 27px 27px 0px; text-align: right; position: absolute; bottom: 0px; right: 0px; text-shadow: 0px 0px 0px #000000;}
+.top-left {font-size:5.33rem; color: #9b9b9b; background: #ffffff; text-align: center; width: 1000px; height: 67px; position: absolute; padding: 36px 0 0 0; top: 0;}
+.bottom-right {font-size:2.33rem; color: #8a2332; line-height: 1.5rem; width: auto; height: 100px; padding: 0 27px 27px 0; text-align: right; position: absolute; bottom: 0; right: 0; text-shadow: 0 0 0 #000000;}
 
 /* Conference Title Logo */
 .title1{color: #B5314C; text-shadow: 1px 1px 3px #c0c0c0;}
 .title2{color: #B5314C; text-shadow: 1px 1px 3px #c0c0c0;}
-.year{color: #B5314C; font-size:0.67em; font-weight: lighter;}
+.year{color: #B5314C; font-size:0.67rem; font-weight: lighter;}
 
 /* Navigation Links (Home, Registration, etc) */
 table.navigation{width:800px;}
-td.navigation{font-size:1.67em; white-space:nowrap; width:20%; text-align:center; vertical-align:middle; padding:0px 0px 0px 0px;}
+td.navigation{font-size:1.67rem; white-space:nowrap; width:20%; text-align:center; vertical-align:middle; padding:0 0 0 0;}
 
 /* Sponsor Images */
 table.sponsors{width:800px;}
-td.sponsor{white-space:nowrap; width:33%; text-align:center; vertical-align:middle; padding:0px 0px 0px 0px;}
+td.sponsor{white-space:nowrap; width:33%; text-align:center; vertical-align:middle; padding:0 0 0 0;}
 td.sponsor img{width: 100%}
 
 /* The Table on the Program Page */
-td.room{padding: 4px 12px 4px 4px; width: 90%; vertical-align:bottom; font-size:1.67em; color: #52739e; height:32px;}
-td.date{white-space:nowrap; width:130px; text-align:right; vertical-align:top; padding:4px 16px 0px 0px;}
-td.title{padding: 4px 12px 4px 4px; width: 90%; vertical-align:top; font-size:1.5em; color: #8a2332; height:32px; font-family:'Roboto Slab',serif; text-shadow: 1px 1px 2px #d0d0d0; }
-td.title-special{padding: 4px 12px 4px 4px; width: 90%; vertical-align:top; font-size:1.67em; color: #52739e; height:32px; font-family:'Roboto Slab',serif; text-shadow: 1px 1px 2px #d0d0d0;}
-td.speaker{padding: 4px 12px 4px 4px; font-style: italic; font-size:1em; max-height:999999px}
-td.abstract{padding: 4px 12px 12px 4px; font-size:1em; max-height:999999px}
+td.room{padding: 4px 12px 4px 4px; width: 90%; vertical-align:bottom; font-size:1.67rem; color: #52739e; height:32px;}
+td.date{white-space:nowrap; width:130px; text-align:right; vertical-align:top; padding:4px 16px 0 0;}
+td.title{padding: 4px 12px 4px 4px; width: 90%; vertical-align:top; font-size:1.5rem; color: #8a2332; height:32px; font-family:'Roboto Slab',serif; text-shadow: 1px 1px 2px #d0d0d0; }
+td.title-special{padding: 4px 12px 4px 4px; width: 90%; vertical-align:top; font-size:1.67rem; color: #52739e; height:32px; font-family:'Roboto Slab',serif; text-shadow: 1px 1px 2px #d0d0d0;}
+td.speaker{padding: 4px 12px 4px 4px; font-style: italic; font-size:1rem; max-height:999999px}
+td.abstract{padding: 4px 12px 12px 4px; font-size:1rem; max-height:999999px}
 td.abstract img{display: block; margin: 4px auto 8px auto}
 table.plenary{padding-top: 8px; background: #ffffff;}
 
 /* Registration and Directions iframes and Images */
-iframe.registration{display:block; margin:1em auto 2em auto; width:700px; height:1400px; border:none;}
-iframe.directions{display:block; margin:1em auto 2em auto; width:800px; height:400px; border:none;}
-img.center{display:block; width:67%; margin:1em auto 2em auto;}
+iframe.registration{display:block; margin:1rem auto 2rem auto; width:700px; height:1400px; border:none;}
+iframe.directions{display:block; margin:1rem auto 2rem auto; width:800px; height:400px; border:none;}
+img.center{display:block; width:67%; margin:1rem auto 2rem auto;}
 
 /* Flyer Images */
 table.flyers{width:800px;}
-td.flyer{white-space:nowrap; width:50%; text-align:center; vertical-align:middle; padding:0px 0px 0px 0px;}
+td.flyer{white-space:nowrap; width:50%; text-align:center; vertical-align:middle; padding:0 0 0 0;}
 td.sponsor img{width: 100%}
 
-footer{font-size:0.875em; margin-top:12em; text-align:center;}
+footer{font-size:0.875rem; margin-top:12rem; text-align:center;}
 
 /* My hacky way of making the site mobile-friendly */
 @media only screen and (max-width: 1100px) {
-    h2{font-size:3.00em;}
-    p{font-size:1.5em; line-height:1.5em;}
-    th,td,tr{font-size:1.5em; line-height:1.5em;}
-    td.date{font-size:1em; padding-top:0.5em;}
-    td.navigation{font-size:1.5em; padding:0px 20px 0px 20px;}
-    table.footer{font-size:0.33em;}
+    h2{font-size:3.00rem;}
+    p{font-size:1.5rem; line-height:1.5rem;}
+    th,td,tr{font-size:1.5rem; line-height:1.5rem;}
+    td.date{font-size:1rem; padding-top:0.5rem;}
+    td.navigation{font-size:1.5rem; padding:0 20px 0 20px;}
+    table.footer{font-size:0.33rem;}
 }
 
diff --git a/cwlcon2024-site/index.html b/cwlcon2024-site/index.html
index 2cffec7..57cc58f 100644
--- a/cwlcon2024-site/index.html
+++ b/cwlcon2024-site/index.html
@@ -9,7 +9,7 @@
     <meta name="resource-type" content="document">
     <meta name="distribution" content="global">
     <meta name="KeyWords" content="Conference">
-    <title>CWLCon</title>
+    <title>CWLCon 2024</title>
 </head>
 
 <body>
@@ -24,61 +24,57 @@
         </div>
     </div>
 
-<table class="navigation">
-    <tr>
-        <td class="navigation">
-            <a class="current" title="Conference Home Page" href="..">Home</a>
-        </td>
-        <td class="navigation">
-            <a title="Register for the Conference" href="registration">Registration (TBA)</a>
-        </td>
-        <td class="navigation">
-            <a title="Conference Program" href="program">Program (TBA)</a>
-        </td>
-        <td class="navigation">
-            <a title="Directions to the Conference" href="directions">Directions (TBA)</a>
-        </td>
-        <td class="navigation">
-            <a title="Conference Flyer" href="flyer">Flyer</a>
-        </td>
-    </tr>
-</table>
-
-<h2>CWLCon 2024</h2>
-<p>
-    We are hosting a CWL Conference in Europe in May 2024!
-</p>
-<p>
-    Submissions will open in February 2024
-</p>
-
-<h2>Call for Submissions</h2>
-<p>
-    JOIN US FOR THE 4th ANNUAL CWL CONFERENCE & 10th ANNIVERSARY CELEBRATION
-
-    Founded in 2014, the Common Workflow Language (CWL) project originated from the conversations at the Bioinformatics Open Source Conference CodeFest.
-    CWL is a well-known and advocated standard for describing how to run command line tools and connect them to create workflows. 
-    The CWL annual conference was first held online in 2021. It has since been held online and hybrid mode in the past two years.
-
-    Building on the experience from the past, the CWL 2024 conference will be officially hosted as a hybrid event in the historical city of Amsterdam. 
+    <table class="navigation">
+        <tr>
+            <td class="navigation">
+                <a class="current" title="Conference Home Page" href="..">Home</a>
+            </td>
+            <td class="navigation">
+                <a title="Register for the Conference" href="registration">Registration (TBA)</a>
+            </td>
+            <td class="navigation">
+                <a title="Conference Program" href="program">Program (TBA)</a>
+            </td>
+            <td class="navigation">
+                <a title="Directions to the Conference" href="directions">Directions (TBA)</a>
+            </td>
+            <td class="navigation">
+                <a title="Conference Flyer" href="flyer">Flyer</a>
+            </td>
+        </tr>
+    </table>
+
+    <h2>CWLCon 2024</h2>
+    <p>
+        We are hosting a CWL Conference in Europe in May 2024!
+    </p>
+    <p>
+        Submissions will open in February 2024
+    </p>
+
+    <h2>Call for Submissions</h2>
+
+    <p>JOIN US FOR THE 4th ANNUAL CWL CONFERENCE & 10th ANNIVERSARY CELEBRATION</p>
+
+    <p>Founded in 2014, the Common Workflow Language (CWL) project originated from the conversations at the Bioinformatics Open Source Conference CodeFest.
+    CWL is a well-known and advocated standard for describing how to run command line tools and connect them to create workflows.
+        The CWL annual conference was first held online in 2021. It has since been held online and hybrid mode in the past two years.</p>
+
+    <p>Building on the experience from the past, the CWL 2024 conference will be officially hosted as a hybrid event in the historical city of Amsterdam.
     The conference will feature contributed talks from speakers, vendors, training sessions and a hackathon / collaboration-fest.
-    There will also be many networking opportunities at the conference.
+        There will also be many networking opportunities at the conference.</p>
 
-    The conference organising committee will like to invite abstracts from any discipline. 
-    The target audiences for this conference are broad and include existing or potential CWL users, research software engineers and workflow engine developers. 
-    We envisage to provide immersive learning opportunities and stimulating environment for individuals from varying background and interests.
+    <p>The conference organising committee will like to invite abstracts from any discipline.
+    The target audiences for this conference are broad and include existing or potential CWL users, research software engineers and workflow engine developers.
+        We envisage to provide immersive learning opportunities and stimulating environment for individuals from varying background and interests.</p>
 
-    Moreover, our conference is dedicated to fostering inclusiveness, urging active involvement, and welcoming contributions from individuals with diverse backgrounds.
-    Collectively, we aim to create a collaborative and supportive environment that fosters the development of ideas and solutions. 
+    <p>Moreover, our conference is dedicated to fostering inclusiveness, urging active involvement, and welcoming contributions from individuals with diverse backgrounds.
+    Collectively, we aim to create a collaborative and supportive environment that fosters the development of ideas and solutions.</p>
 
-    Should you have any questions or concerns, please do not hesitate to reach out to the organisers directly.
+    <p>Should you have any questions or concerns, please do not hesitate to reach out to the organisers directly.</p>
 
+    <h2>Organizers</h2>
 
-</p>
-
-
-<h2>Organizers</h2>
-<p>
     <ul>
         <li><a href="https://github.com/mr-c">Michael Crusoe</a></li>
         <li><a href="https://github.com/GlassOfWhiskey">Iacopo Colonnelli</a></li>
@@ -90,19 +86,17 @@
         <li><a href="https://github.com/inutano">Tazro Inutano Ohta</a></li>
         <li><a href="https://github.com/tom-tan">Tomoya Tanjo</a></li>
     </ul>
-</p>
 
-If you would like to be a conference organiser please reach out to one of us through the <a href="https://matrix.to/#/#common-workflow-language_common-workflow-language:gitter.im">Gitter App</a>.
+    <p>If you would like to be a conference organiser please reach out to one of us through the <a href="https://matrix.to/#/#common-workflow-language_common-workflow-language:gitter.im">Gitter App</a>.</p>
+
+    <h2>Sponsors</h2>
 
-<h2>Sponsors</h2>
-<table class="sponsors">
     <p> This could be your organization!! </p>
-</table>
 
-<footer>
-    &copy; Conference Organizers
-    &nbsp;|&nbsp; Design by <a href="https://github.com/mikepierce">Mike Pierce</a>
-</footer>
+    <footer>
+        &copy; Conference Organizers
+        &nbsp;|&nbsp; Design by <a href="https://github.com/mikepierce">Mike Pierce</a>
+    </footer>
 
 </body>
 </html>
```

This renders:

Screen Shot 2023-11-23 at 22 29 10-fullpage

**Comment by kinow** [comment]
We can improve the CSS a bit more. Hi @Fienne. We are in need of a better layout. Are you interested in adding a conference website to your portfolio? We can work together on a new design, very few options so little UIUX, but could still be interesting? WDYT?

**Comment by alexiswl** [comment]
@kinow looks much better! Can you put a PR into the site-template-reset branch?

**Comment by kinow** [comment]
> @kinow looks much better! Can you put a PR into the site-template-reset branch?

Sure thing! Here you go https://github.com/common-workflow-language/cwlcon2024/pull/14

**Comment by alexiswl** [comment]
@mr-c okay to merge?

**Comment by mr-c** [comment]
Go for it!

**Comment by Fienne** [comment]
> We can improve the CSS a bit more. Hi @Fienne. We are in need of a better layout. Are you interested in adding a conference website to your portfolio? We can work together on a new design, very few options so little UIUX, but could still be interesting? WDYT?

Hi @kinow, yes I am interested. Right now, I am a little busy with school and I can be able to work on it on Monday. Is that okay?

**Comment by kinow** [comment]
That's great! It will be fun to work together again! No hurry at all, @Fienne , we can improve it over the next month(s). This is the current site: https://www.commonwl.org/conferences/2024/ (there is definitely room for improvement :slightly_smiling_face: )

**Pull request merged**
