### PR TITLE
Add 2 columns, add cards (avatars/organizers), placeholder for map, and a few more CSS improvements

### LINKED ISSUE #26: Improve layout, UIUIX, Look n Feel
Placeholder for the updates for the UIUX.

@alexiswl creating this one to track all requirements in a single place. @Fienne, you can look at just this one whenever you have time later :+1: and it should contain links to the open issues that are related to design, UIUX, etc.

- [x] improve the general layout (alignment, consistency, typography, colors, ...)
  - I think it might be nice if we are able to offer:
    - [ ] dark theme
    - [ ] good accessibility (including but not only color-blindness)
- [x] mobile friendly, small https://github.com/common-workflow-language/cwlcon2024/issues/24
- [x] modify how location & date are displayed (that issue will be used for other topics) https://github.com/common-workflow-language/cwlcon2024/issues/18
- [ ] we need to make the website look more fun https://github.com/common-workflow-language/cwlcon2024/issues/29

### LINKED ISSUE #29: Make the website look more fun
It is a 10 year celebration, we need to make our website look at bit happier than the current version we have.

Here's some ideas from today's (2023-11-24) meeting:

- Michael: What can we do to make this feel more fun? It is supposed to be a celebration 😃
  - Add some splash of colors e.g. https://www.open-bio.org/events/bosc-2023/ 
  - Pictures of happy CWL people?
  - Ideas from https://www.open-bio.org/events/bosc-2023/  ?

### PR DESCRIPTION
**Pull request by kinow**
Closes #26 
Closes #29 

I built this on top of #47 , but if others prefer I can push to that one and have everything reviewed in a single PR (otherwise I will rebase and resolve any conflicts here later).

Some screenshots below, large and smaller viewports (images are not final, nor text/colors/etc., feel free to suggest any changes).

image

image

### CODE REVIEW

**Comment by kinow** [comment]
After these two, over the next days I will submit one or two other PRs for SEO tags (so it's easier to search/find now and after the conf), and for accessibility (improve contrast, use WAVE to test it, and use a screen reader to navigate the site :+1: ). Then I think the site layout tasks will be over, and I will focus on that Zotero list and translate/contribute-a-thon :wave:

**Comment by alexiswl** [comment]
This looks great! How does it handle when the columns aren't of equal length? i.e Registrations page will be a short paragraph while the Program contents will likely become quite long?

**Comment by kinow** [comment]
> This looks great! How does it handle when the columns aren't of equal length? i.e Registrations page will be a short paragraph while the Program contents will likely become quite long?

In that case it might be easier to shuffle things around to find some balance 

It will just keep the content of both aligned at the top, both columns with the same height.

**Review by alexiswl — APPROVED** [review]

**Comment by kinow** [comment]
I was creating a separate PR when I realized it would be simpler to push a commit here. Last commit updates the venue (confirmed with @mr-c via element). I used the details from the university website, copying the exact Google Maps link. The address was added with the `<address>` HTML tag as that simplifies for SEO and when there tools/browsers to identify there is an address in that page.

Leaving the date for the week until we have defined the agenda for the online part too, and other timezones, etc.

**Comment by alexiswl** [comment]
@kinow are you happy to merge this?

**Comment by kinow** [comment]
> @kinow are you happy to merge this?

Was waiting to see if @mr-c wanted to review this one too.

**Pull request merged**
