### PR TITLE
Use columns for the new content

### PR DESCRIPTION
**Pull request by kinow**
Great work on updating the website! I thought about adding some more colours, an illustration (from storyset - free with attribution which I added to footer), and shuffling things around to better use the page space. I did that by shortening a few words (probably <10 words?), moving some text, and using multiple columns for larger screen, which is rendered stacked on mobile.

Preview below:

image

Green is normally used to tone down when you have strong/lots of red (they are complementary colors), so I picked the one green we already had on the page, from the terrain of google map (we have a Google Maps screenshot from the uni location).

There is a link that's rendered as a button to, hopefully, call attention to users that they can submit a talk. I was going to do the same with registration, but thought it could confuse users and they could end up not submitting. The Submission Form button has a quick animation, but shouldn't bother users I believe. (The envelope "flies" when you hover your mouse over it.)

The major change regarding columns was in the program, where I used columns to reduce the white space, trying to keep things aligned (to look like a grid -- which is normally easier for the human eye).

I think that's the summary of changes..

Cheers

### CODE REVIEW

**Comment by kinow** [comment]
(push-forced after editing the commit twice - 1st because I broke the link to organizers, and 2nd time to add back to top in the program section; done now)

**Comment by alexiswl** [comment]
Oh this layout looks amazing! 

Can we swap the green for the blue used in the health and safety? I think it would make it less contrasty?

**Comment by kinow** [comment]
> Oh this layout looks amazing!

:tada: 

> Can we swap the green for the blue used in the health and safety? I think it would make it less contrasty?

The idea was exactly to use contrast to catch the user's eyes, e.g. https://www.linkedin.com/pulse/importance-color-contrast-web-design-sachin-datta. I had to search for a link on web design, because I use it more in drawings/paintings... you use that to drive the user's eyes on a drawing/painting, similar principle used in marketing/web design/cartoons, etc.

I thought the light blue would look too similar to the other section, and really wanted to call attention to the submission area and the submission button (thus the red button too). But maybe blue looks better (these design rules exist to help, but are not mandatory :slightly_smiling_face:). So here are a couple of previous, one of green, and one with blue, but now I changed the SVG background that was light gray (hard to read with green or blue).

TODO

**Comment by alexiswl** [comment]
Thanks Bruno, it looks great! 

I did initially try the two columns for the program but ran into a bit of a mess with the training event.  

If we split the week 2 program view into four quadrants, chronologically we're going quadrant 4, quadrant 1, quadrant 2, quadrant 3, quadrant 4.  

image

**Comment by kinow** [comment]
> Thanks Bruno, it looks great!
> 
> I did initially try the two columns for the program but ran into a bit of a mess with the training event.
> 
> If we split the week 2 program view into four quadrants, chronologically we're going quadrant 4, quadrant 1, quadrant 2, quadrant 3, quadrant 4.
> 
> image

Ah! I see, I was trying to align things but didn't spot that that was putting them out of chronological order! Back to whiteboard, let me try to move them back... (will try to update it today over the next hours)

Thanks @alexiswl

**Comment by kinow** [comment]
Moved the content back to a single column, and also added the VU uni sponsor logo.

image

**Review by alexiswl — APPROVED** [review]
Looks great!

**Comment by kinow** [comment]
Thank you @alexiswl . I think there is no urgency on merging it, so will leave it open to see if @mr-c wants to take a quick look at the latest screenshot above :+1:

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
Thank you @kinow !

**Pull request merged**
