### PR TITLE
Added calendar invites for each session

### LINKED ISSUE #77: Add calendar invites for each session

### PR DESCRIPTION
**Pull request by alexiswl**
Added iCal files, Google calendar links and outlook links

### CODE REVIEW

**Review by mr-c — CHANGES_REQUESTED** [review]
Hmm. I was going to send a calendar invite to registered participants via email. It would also include the in-person meeting instructions for the hybrid sessions. Let me think on this before merging

**Comment by alexiswl** [comment]
> Hmm. I was going to send a calendar invite to registered participants via email. 

Yes, can we not have both? What about those that haven't registered, or don't regularly check their emails? Or register after the email is sent?

> It would also include the in-person meeting instructions for the hybrid sessions.

I think we can provide both options?

**Review by kinow — COMMENTED** [review]
Maybe there could be an issue in case the calendar needs to be updated; not sure if those that downloaded from the site will receive the updates... or maybe there's some privacy issue... But otherwise it looks like a good idea to me :+1:

**Comment by mr-c** [comment]
This is a good idea for next year! Sorry I couldn't make a decision in time.

**Comment by alexiswl** [comment]
> This is a good idea for next year! Sorry I couldn't make a decision in time.

Yes, I do think we would need to tie them to a proper Google or Outlook Calendar invite link though, so that if plans do change, invitees are updated (I actually don't actually know if this is feasible)

**Pull request closed without merging**
